### ISSUE TITLE
Masago not working

### ISSUE THREAD

**Issue by EgOCrispy** [malaow3/AniTracker#2]
When running the script it tells me: go run main.go
2023-04-01 03:51:28.901 [main.go:59][main()] [INFO] Starting masago-roll v0.1.0
2023-04-01 03:51:29.117 [trunk.go:30][CheckErr()] [PANI] etp_rt not found
panic: (*logrus.Entry) 0xc00010e150

goroutine 1 [running]:
github.com/sirupsen/logrus.(Entry).log(0xc00010e0e0, 0x0, {0xc000024290, 0x10})
[github.com/sirupsen/logrus@v1.8.1](mailto:github.com/sirupsen/logrus@v1.8.1)/entry.go:259 +0x43e
github.com/sirupsen/logrus.(Entry).Log(0xc00010e0e0, 0x0, {0xc000687f08?, 0x99f654?, 0xc0000eedc0?})
[github.com/sirupsen/logrus@v1.8.1](mailto:github.com/sirupsen/logrus@v1.8.1)/entry.go:293 +0x4f
github.com/sirupsen/logrus.(Logger).Log(0xc00010e000, 0x0, {0xc000687f08, 0x1, 0x1})
[github.com/sirupsen/logrus@v1.8.1](mailto:github.com/sirupsen/logrus@v1.8.1)/logger.go:198 +0x65
github.com/sirupsen/logrus.(Logger).Panic(...)
[github.com/sirupsen/logrus@v1.8.1](mailto:github.com/sirupsen/logrus@v1.8.1)/logger.go:247
github.com/sirupsen/logrus.Panic(...)
[github.com/sirupsen/logrus@v1.8.1](mailto:github.com/sirupsen/logrus@v1.8.1)/exported.go:129
github.com/malaow3/trunk.CheckErr(...)
[github.com/malaow3/trunk@v0.0.0-20210918025242-29a849bb29f8](mailto:github.com/malaow3/trunk@v0.0.0-20210918025242-29a849bb29f8)/trunk.go:30
main.main()
main/main.go:69 +0x1ef
panic: exit status 2

goroutine 1 [running]:
main.main()
/home/runner/masago/main.go:25 +0x1ab
exit status 2
exit status 1

**Comment by malaow3** [comment]
Hey there! This tool unfortunately broke sometime within the last couple of months... Seems like there was an overhaul to the Crunchyroll internal API (and they don't have a public facing one) so some of the endpoints I was relying on broke. I haven't had time to fix this yet and was actually planning to do a complete re-write in a different programming language as a learning exercise but just haven't had the time to dedicate to finishing -- although I am pretty close to something that could be "passable". If you keep an eye on my anilist profile (https://anilist.co/user/OnionSupreme/) I'll make an updated forum post whenever I get time to complete the update! Apologies for the inconvenience and thanks in advance for your patience and interest!

**Comment by EgOCrispy** [comment]
Got it! I appreciate the time and effort you put into this. I'll definitely be on the look out for that updated forum post. Thanks again for taking the time out your day to respond and fixing it:)

**Comment by malaow3** [comment]
Anytime! This is just more motivation to continue the project -- kind of lost interest in it since I felt like a) I was the only one who used it and b) I haven't been watching as much as I used to LOL. Thank you again for the interest in the project!

**Comment by EgOCrispy** [comment]
yeah ofc you're welcome
